/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        // Neo-Brutalist Core Palette mapped to native CSS Variables
        "neo-yellow": "var(--color-neo-yellow)",
        "neo-cyan": "var(--color-neo-cyan)",
        "neo-pink": "var(--color-neo-pink)",
        "neo-green": "var(--color-neo-green)",
        "neo-black": "var(--color-neo-black)",
        "neo-bg": "var(--color-neo-bg)",
        "neo-surface": "var(--color-neo-surface)",
        "neo-on-accent": "var(--color-neo-on-accent)",

        // Stitch Design Tokens
        "surface": "var(--color-neo-surface)",
        "surface-dim": "var(--color-neo-surface-dim)",
        "surface-bright": "var(--color-neo-surface)",
        "surface-container-lowest": "var(--color-neo-surface-low)",
        "surface-container-low": "var(--color-neo-surface-low)",
        "surface-container": "var(--color-neo-surface-container)",
        "surface-container-high": "var(--color-neo-surface-high)",
        "surface-container-highest": "var(--color-neo-surface-highest)",
        "on-surface": "var(--color-neo-text)",
        "on-surface-variant": "var(--color-neo-text-muted)",
        "outline": "var(--color-neo-border)",
        "outline-variant": "var(--color-neo-border)",
        "primary": "var(--color-neo-yellow)",
        "on-primary": "var(--color-neo-on-accent)",
        "primary-container": "var(--color-neo-yellow)",
        "on-primary-container": "var(--color-neo-on-accent)",
        "secondary": "var(--color-neo-cyan)",
        "on-secondary": "var(--color-neo-on-accent)",
        "secondary-container": "var(--color-neo-cyan)",
        "on-secondary-container": "var(--color-neo-on-accent)",
        "tertiary": "var(--color-neo-pink)",
        "on-tertiary": "var(--color-neo-on-accent)",
        "tertiary-container": "var(--color-neo-surface-container)",
        "on-tertiary-container": "var(--color-neo-pink)",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "success": "var(--color-neo-green)",
        "on-success": "var(--color-neo-on-accent)",
        "success-container": "#d1fae5",
        "background": "var(--color-neo-bg)",
        "on-background": "var(--color-neo-text)",
      },
      fontFamily: {
        space: ["'Space Grotesk'", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        "headline-lg": ["'Space Grotesk'", "sans-serif"],
        "headline-xl": ["'Space Grotesk'", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "stats-lg": ["'JetBrains Mono'", "monospace"],
        "label-caps": ["'JetBrains Mono'", "monospace"],
      },
      boxShadow: {
        "neo": "4px 4px 0px 0px var(--shadow-neo-color)",
        "neo-lg": "6px 6px 0px 0px var(--shadow-neo-color)",
        "neo-sm": "2px 2px 0px 0px var(--shadow-neo-color)",
        "brutal": "4px 4px 0px 0px var(--shadow-neo-color)",
        "brutal-lg": "6px 6px 0px 0px var(--shadow-neo-color)",
        "brutal-xl": "8px 8px 0px 0px var(--shadow-neo-color)",
        "brutal-sm": "2px 2px 0px 0px var(--shadow-neo-color)",
      },
      borderWidth: {
        "3": "3px",
      },
      spacing: {
        "gutter": "16px",
        "stack-gap": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      }
    },
  },
  plugins: [],
}
