/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Controllo dello stato di salute del server (Health Check)
         * @description Endpoint per monitoraggio e cloud uptime (zero database overhead).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server attivo e funzionante */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                            uptime?: number;
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrazione nuovo account
         * @description Crea un nuovo profilo utente, cripta la password con bcrypt e restituisce il JWT token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterDTO"];
                };
            };
            responses: {
                /** @description Utente registrato con successo */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Validazione fallita o email/username già registrati */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accesso utente (Login)
         * @description Verifica le credenziali (email o username) e restituisce il JWT Bearer token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginDTO"];
                };
            };
            responses: {
                /** @description Login effettuato con successo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Credenziali non valide */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profilo utente autenticato
         * @description Recupera il profilo dell utente a partire dal token Bearer.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profilo utente recuperato */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfile"];
                    };
                };
                /** @description Non autorizzato (token mancante o scaduto) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Avvio nuova sessione di gioco (Speedrun)
         * @description Inizializza una nuova partita da una pagina casuale verso la pagina obiettivo (Federico II).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StartGameDTO"];
                };
            };
            responses: {
                /** @description Partita avviata con successo */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActiveGameResponse"];
                    };
                };
                /** @description Partita già attiva per questo utente o input non valido */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Non autorizzato */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recupera partita attiva
         * @description Restituisce lo stato della sessione IN_PROGRESS e l HTML della pagina corrente.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Partita attiva recuperata (o null se nessuna attiva) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActiveGameResponse"] | null;
                    };
                };
                /** @description Non autorizzato */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Naviga un link (Step di gioco)
         * @description Esegue un click su un link di Wikipedia. Valida anti-cheat se il link era realmente presente nella pagina.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID univoco della partita */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MakeStepDTO"];
                };
            };
            responses: {
                /** @description Passo eseguito e nuova pagina caricata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActiveGameResponse"];
                    };
                };
                /** @description Link non valido o non presente nella pagina attuale (Anti-cheat) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Non autorizzato */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Partita non trovata o non appartenente all utente */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abbandona partita attiva
         * @description Imposta lo stato della partita corrente su ABANDONED.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID univoco della partita */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Partita abbandonata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Game"];
                    };
                };
                /** @description Non autorizzato */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Partita non trovata */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Classifica globale (Leaderboard)
         * @description Restituisce i migliori speedrunner ordinati per minor numero di click e tempo.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Classifica globale recuperata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaderboardEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/completed-games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ultime partite completate
         * @description Restituisce lo storico delle partite concluse con successo e l elenco completo dei passi.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista partite completate */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompletedGameView"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserProfile: {
            /**
             * Format: uuid
             * @example d3b07384-d113-40bf-98bc-e7e0ac05c317
             */
            id: string;
            /**
             * Format: email
             * @example studente@unina.it
             */
            email: string;
            /** @example speedrunner99 */
            username: string;
            /** Format: date-time */
            createdAt: string;
        };
        AuthResponse: {
            user: components["schemas"]["UserProfile"];
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            token: string;
        };
        RegisterDTO: {
            /** Format: email */
            email: string;
            username: string;
            password: string;
        };
        LoginDTO: {
            login: string;
            password: string;
        };
        /** @enum {string} */
        GameStatus: "IN_PROGRESS" | "COMPLETED" | "ABANDONED";
        GameStep: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            gameId: string;
            pageTitle: string;
            stepOrder: number;
            /** Format: date-time */
            createdAt: string;
        };
        Game: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            startPageTitle: string;
            currentPageTitle: string;
            targetPageTitle: string;
            status: components["schemas"]["GameStatus"];
            clickCount: number;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime?: string | null;
            steps?: components["schemas"]["GameStep"][];
        };
        WikiArticleContent: {
            title: string;
            html: string;
            validLinks: string[];
        };
        ActiveGameResponse: {
            game: components["schemas"]["Game"];
            pageContent: components["schemas"]["WikiArticleContent"];
            isGoalReached: boolean;
        };
        StartGameDTO: {
            overrideStartPage?: string;
        };
        MakeStepDTO: {
            targetTitle: string;
        };
        LeaderboardEntry: {
            rank: number;
            username: string;
            completedGames: number;
            bestClicks: number;
            bestTimeSeconds: number;
            totalClicks: number;
        };
        CompletedGameView: {
            /** Format: uuid */
            id: string;
            username: string;
            startPageTitle: string;
            targetPageTitle: string;
            clickCount: number;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            durationSeconds: number;
            steps: components["schemas"]["GameStep"][];
        };
        ErrorResponse: {
            error: string;
            code: string;
            details?: Record<string, never> | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
