/**
 * Application Error Code enum representing standardized, machine-readable error identifiers.
 */
export enum ErrorCode {
  // Authentication & Session
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  USERNAME_ALREADY_TAKEN = 'USERNAME_ALREADY_TAKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Game Lifecycle & Rules
  ACTIVE_GAME_EXISTS = 'ACTIVE_GAME_EXISTS',
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  INVALID_STEP = 'INVALID_STEP',
  CONCURRENT_CONFLICT = 'CONCURRENT_CONFLICT',

  // Wikipedia Integration
  INVALID_WIKI_TITLE = 'INVALID_WIKI_TITLE',
  WIKI_API_ERROR = 'WIKI_API_ERROR',
  WIKI_PAGE_NOT_FOUND = 'WIKI_PAGE_NOT_FOUND',

  // Transport & Middleware
  CORS_NOT_ALLOWED = 'CORS_NOT_ALLOWED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  MALFORMED_JSON = 'MALFORMED_JSON',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
